### ISSUE TITLE
[1.4] Crashing in load

### ISSUE THREAD

**Issue by Thyriel** [raphydaphy/EnhancedProgression#11]
I upgraded from 1.2 to 1.4 (deleted config files just in case too) but seems 1.4 just crashes upon load.
Crashlog: http://pastebin.com/zrwCS92Y

**Comment by raphydaphy** [comment]
You need to install Guide API to get it to work. Get the latest GuideAPI for 1.10.2 (u need the very latest version for it to work as well).

**Comment by Thyriel** [comment]
Thanks. You should probably add it as a dependency on curseforge and setup the requirement in the mod itself (like other mods do) so that forge displays a missing dependency mod upon load instead crashing.

**Comment by raphydaphy** [comment]
yea i cant figure out how to xD will soon tho.
