### ISSUE TITLE
Where to store spells?

### ISSUE THREAD

**Issue by TFSpectre** [raphydaphy/EnhancedProgression#19]
Having started following the guide, I could do with being able to store the spells that are being created as inventory space is at best tight. Ars Magica 2 appears to have a book for storing spells, but sadly the two mods won't work with each other, please advise on a similar method for spell storage as I'm struggling to find one.

**Comment by raphydaphy** [comment]
Theres a thing called the spell bag, im pretty sure its in the book. Craft it by using cryptic transmutation on a bookshelf for 500 essence and then craft the spells with the bag in a crafting grid one at a time to add them to it. Press some key that u set in the controls menu while the bag is in offhand and wand in main hand and it will open a gui that lets u select a spell to cast.
