### ISSUE TITLE
Crash with 1.3 version

### ISSUE THREAD

**Issue by MokahTGS** [raphydaphy/EnhancedProgression#3]
Getting a crash on load with the latest version.

http://pastebin.com/1v4sAu70

**Comment by Morpheus1101** [comment]
I to am getting a crash with latest version on Server & client

Client: https://puu.sh/sGTz9/46aa2e6d81.txt

Server:  https://puu.sh/sGTA9/692649e561.txt

**Comment by raphydaphy** [comment]
Looks like I forgot to rename something to Vitality when I changed the mod name 😕 I'll try to fix it now 😟
